### ISSUE TITLE
Implement stage-3 proposal babel plugin

### ISSUE THREAD

**Issue by induratized** [pngwn/svelte-react-template#2]
Need to implement stage-3 features like `"@babel/plugin-proposal-optional-chaining"` ( `?.` operator ).
`rollup.config.js` babel() script below
```
resolve()... ,
commonjs()...,
babel({
          extensions: ['.svelte', '.js', '.mjs', '.html'],
          presets: [
            [
              '@babel/preset-env',
              {
                targets: {
                  node: '9'
                },
                "modules": false
              }
            ]
          ]
          "plugins": ["@babel/plugin-proposal-optional-chaining"]
        }),
```

PARSE ERROR
```
ParseError: Unexpected token
    at error$1 (/Users/.../node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$2.error (/Users/.../node_modules/svelte/src/compiler/parse/index.ts:93:3)
    at Parser$2.acorn_error (/Users/.../node_modules/svelte/src/compiler/parse/index.ts:86:8)
```

**Comment by pngwn** [comment]
This requires a preprocessor in addition to a babel plugin that works on JS files, as the JS in svelte components is parsed by acorn which only supports standard JS features. I won't be adding it to the template as this is just a bare-bones starter template without any special cases handled.
